# Use the parent analysis options settings and enable null-experiment.

include: ../../analysis_options.yaml

analyzer:
  errors:
    always_require_non_null_named_parameters: false # not needed with nnbd
    type_init_formals: false # https://github.com/dart-lang/linter/issues/2192
    unrelated_type_equality_checks: false # https://github.com/dart-lang/linter/issues/2196
    void_checks: false # https://github.com/dart-lang/linter/issues/2185
    unnecessary_null_comparison: false # Turned off until null-safe rollout is complete.
